[package]
name = "npcnix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
strip = "debuginfo"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive", "env"] }
tar = "0.4.38"
tracing = "0.1.37"
ureq = { version = "2.6.2", features = ["rustls-native-certs"] }
url = "2.3.1"
zstd = "0.12.3"
