[package]
name = "npcnix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
strip = "debuginfo"

[dependencies]
anyhow = "1.0.70"
aws-config = { version = "0.55.0", default-features = false, features = ["native-tls"] }
aws-sdk-s3 = "0.25.1"
clap = { version = "4.2.1", features = ["derive", "env"] }
tokio = { version = "1.27.0", features = ["macros", "net", "rt", "rt-multi-thread"] }
tracing = "0.1.37"
url = "2.3.1"
